apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: integration-hub
type: Opaque
stringData:
  connectionstring: "Host=postgres-service;Port=5432;Database=inbound_db;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-orchestrator
  namespace: integration-hub
type: Opaque
stringData:
  connectionstring: "Host=postgres-service;Port=5432;Database=orchestrator_db;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-outbound
  namespace: integration-hub
type: Opaque
stringData:
  connectionstring: "Host=postgres-service;Port=5432;Database=outbound_db;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: integration-hub
type: Opaque
stringData:
  connectionstring: "amqp://guest:guest@rabbitmq-service:5672/"

